---
sudo: required
language: python
services: docker

env:
  - version=">=2.6,<2.7" distro="centos-6"
  - version="" distro="centos-6"
  - version="devel" distro="centos-6"
  - version=">=2.6,<2.7" distro="centos-latest"
  - version="" distro="centos-latest"
  - version="devel" distro="centos-latest"

matrix:
  fast_finish: yes
  allow_failures:
    - env: version="devel" distro="centos-6"
    - env: version="devel" distro="centos-latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - if [ "${version}" != "devel" ] ; then pip install ansible"${version}" ; fi
  - if [ "${version}" = "devel" ] ; then pip install git+https://github.com/ansible/ansible.git@devel ; fi
  - pip install molecule
  - pip install docker

script:
  - if [ "${expectation}" = "fail" ] ; then ! molecule test --scenario-name "${distro}" ; else molecule test --scenario-name "${distro}" ; fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "xIMAgMyfIEpvhCSbIfWaAyLzxiz4KgNT2Q2KeRm3bczrmPU2R0HUFVZWb9Tth4psKnvHpYcbQQYVqnebPizBR2oJo+fEXGL0Ca3LDOswMmB0pN7ldtbZwTOwjKN9NEcK37QHikfGy5PwAbnVsOy/MUcXOEvKykKj1OIjXkMukHWv3RLaoua8sYOl/Tyh4pG2htDCOLufnbpm1tHNw3VHDZ6pdJ59cArM5EUW0ha+Ib+Rm28YmTd00Pgd0BBl/vdnpRiENxxxP8QWpRQCAwWk0mmRs6vJN/mND9G0jw/0OKF47Qh3RUX/dPmLamdRQUgs1N6lxAuhXOnJUQYpZpsJimnSZmJt1+iTJI3BiFCHW3VBE9xM1rcj/6wZIpP3g0AYO5ID26bpyxwp/p4eBQubkIsx3sSwDqX+EIJEHtsAdyrYPlzqJuEKlmLPcMIMD8QbV0iS0GPBT0JShKNUiyMrK+7AEqefbKDDwR2ZlSL9XBdrHTGRwNdJ48xOoaBwoYVy67Wr6vF1GEzluUAND2v2TbeEqyKIcITiLB6/A6ck8ubX7oNxHw1chF2nDpf1dN9fspgnlSXnjTaGREH65WUQV387kFSSAX5qrpUVXatYr4pZTjJ5P2Y463Gp7liU0ES6ZgfQUJ3/UXaHVPA8nHUxLyIaM5q+xK0+5xkWnDcTJbA="
  email: false
