---
sudo: required
language: python
services: docker

env:
  - version=">=2.7,<2.8" distro="centos-7"
  - version="" distro="centos-7"
  - version="devel" distro="centos-7"
  - version=">=2.7,<2.8" distro="centos-latest"
  - version="" distro="centos-latest"
  - version="devel" distro="centos-latest"

matrix:
  allow_failures:
    - env: version="devel" distro="centos-7"
    - env: version="devel" distro="centos-latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - if [ "${version}" != "devel" ] ; then pip install ansible"${version}" ; fi
  - if [ "${version}" = "devel" ] ; then pip install git+https://github.com/ansible/ansible.git@devel ; fi
  - pip install molecule
  - pip install docker

script:
  - if [ "${expectation}" = "fail" ] ; then ! molecule test --scenario-name "${distro}" ; else molecule test --scenario-name "${distro}" ; fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "rkdtdmxkSWkJWyXPs5B3gXBQdFX0B8cmSGRSiXJVLChj0tvOyk7yqgBdW9K7ArTnWOzhcVa/gSBJ9+XSyauv1anCC4VNbiKuzcwchQgEbTzbQ9EF9Ky65Sqr08RiCST4B8q16GeqRUXRKXTLPnXkUPVSyzvOFzJE3Ul74OILjhb65VrQWVhwcVnb8ptXTOCt0wWdNRXWz+BZH4Sm9WbRp9vf6lJX26Yp5FJEova+gaK0uzokczhTbYE2t0NkSxlfIh9tRuaZQ0UpKd/BLfwuNBFEsdos8MBMPfxIkTwKL483V4FhZSK3VBL/FsOWdskLpt6JeS+DuO6h2S2aY4dSuTSK8A1LuxEkwio3z8ilWyV5hVZmkft0yUeMqIXqID8v9L6f3Vfxk9G//nnLNUlwnmBKDHvGgeSctm/XiE+qdS7yM4ZPSLXmFAtc4ibZUe1jHHcLMORfYxjz4kkuL/mECwFYxis3hBmrLw1/CnhdUhx+MAUxN7ld2kXMMo6j67nNaMcz3Lcb4KqSGYLBQ3H8vQvBMDCjYfqih9N/ZPHzON8u8Kr2ezy+80wwjSCwCl7grqe8hTuZQPQKgWfzNGZ3H0qTKuOf+d3iLw5jhcn8/Wrotn6UANJ74BHpszfADEVlCpXCUWOcSS2LPYQgLVA1ekGZbD39Lp0dngY3Nw1im2I="
  email: false
