---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="alpine" tag="latest"
    - image="alpine" tag="edge"
    - image="amazonlinux" tag="1"
    - image="centos" tag="7"
    - image="debian" tag="latest"
    - image="debian" tag="bullseye"
    - image="fedora" tag="31"
    - image="fedora" tag="latest"
    - image="opensuse" tag="latest"
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="bionic"
    - image="ubuntu" tag="xenial"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    rooms:
      - secure: "XoPL4K0Z8IfjHGqBtyK3sCfV4pd+9TgGScS56tRAb8mrzZ2EMbjYWP2FxCvMAuwJJxcpGVjR6AKBSiays5y2cefsYLJoCRoT499onLSTF3obovWs7qW0fG8n2DlcukIZWeA8gf6rdKEp+KK++ShnlJceUB7PyeyF6aKyBVCtPrNAoyR259uAsmNcjc6OkC1y9RWDeCNraLWy2bRHPX5xan5yDtlcC37kCS5LtZ6QoWzpYia5o5Dc3NLFcc4BQ8/AFXPwUdjYQsv8iG3FD7uxRHLZGJKFoGuDySEux8no8YrgdZWwPgaM8H7M5+gr8D3BP945HuSgSm/9CGrfexnncm7NIhzrupgRcdHm0DjuW7r8RIfbvibLLDoukSbwhHhCIwWRAQSw8PLLQRtdBxnncdgZ3YR68N/7a8UOL+F+8yaH2OvTRh7uTTkx/YsUBBgudsY0rV/GyceCRf5vuC2z5eKIskuFP3Q/fTf3SjfssuNZ7k5lVBDvqzFbzPIHtzHaIRRDrTxONGvnJEohPqjl6Jk0uY+kMSlUaFpfSiBUWZtN7NVGJqJvMGCYRvJgH8TnQJTg7ItPBXgfR/Um0gtj5emGXMTnnzLwDwx53/P/fqXW8b0OkU27UhAFq2h1hKedV/yYXxbM7jSqBzh05W5XrHomu05xCHVFgDulgA5+zFQ="
  email: false
