---
# tasks file for scl
- name: install centos-release-scl
  package:
    name: centos-release-scl
    state: "{{ scl_package_state }}"
  when:
    - ( ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux" )
