---
# tasks file for scl
- name: install centos-release-scl
  package:
    name: centos-release-scl
    state: present
  when:
    - ansible_distribution == "CentOS"
  register: scl_install_centos_release_scl
  until: scl_install_centos_release_scl is succeeded
  retries: 3
